Post on the revamped MongoDB cache store
infinispan/infinispan.github.io pull request #317
Opened 2023-05-04 21:36 UTC by antoniomacri

Trying to document the work done here: https://github.com/infinispan/infinispan-cachestore-mongodb/pull/23

2023-05-06 13:53 UTC, tristantarrant commented on _data/authors.yml
> +  image: /assets/images/blog/authors/antoniomacri.jpg
No bio ? :stuck_out_tongue_closed_eyes:

2023-05-06 13:54 UTC, tristantarrant commented on _posts/2023-05-04-reviving-mongodb-cachestore.adoc
> +Since the Infinispan cache store API is now fully reactive, also the store has been modified to use the reactive MongoDB driver.
"the store has also been modified"

2023-05-06 13:54 UTC, tristantarrant commented on _posts/2023-05-04-reviving-mongodb-cachestore.adoc
> +This should be the most efficient way, but it makes harder to inspect the documents stored in Mongo.
"it makes it harder"

2023-05-06 13:54 UTC, tristantarrant requested changes
Just some minor changes

2023-05-09 21:58 UTC, antoniomacri commented on _posts/2023-05-04-reviving-mongodb-cachestore.adoc
> +Since the Infinispan cache store API is now fully reactive, also the store has been modified to use the reactive MongoDB driver.
Changed, thanks.

2023-05-09 21:58 UTC, antoniomacri commented on _posts/2023-05-04-reviving-mongodb-cachestore.adoc
> +This should be the most efficient way, but it makes harder to inspect the documents stored in Mongo.
Fixed.

2023-06-28 19:41 UTC, karesti commented
@antoniomacri please squash the commits and we can plan for publishing, what do you think @tristantarrant  @ryanemerson ?

2023-06-28 20:57 UTC, antoniomacri commented
@karesti done, thanks!

2023-06-30 08:46 UTC, ryanemerson approved these changes
LGTM. Thanks for all the hard work on this @antoniomacri

2023-06-30 09:23 UTC, merged